services:
  db:
    image: postgres:18-alpine
    container_name: para_postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: para_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
